#!/bin/bash

echo "🔧 JSON Parse Error Debug - Encounter Endpoint"
echo "==============================================="

echo ""
echo "🚨 PROBLEM TESPİT EDİLDİ:"
echo "   ❌ Frontend: POST /api/encounter/start"
echo "   ✅ Backend: POST /api/doctor/encounters"
echo "   ❌ Endpoint mismatch → 404 → HTML response (index.html)"
echo "   ❌ JSON.parse() HTML'i parse edemiyor → SyntaxError"

echo ""
echo "✅ DOĞRU ENDPOINT BİLGİSİ:"
echo "   📄 POST /api/doctor/encounters"
echo "   🔐 Auth: await verifyDoctorToken(req)"
echo "   📥 Input: { patient_id, notes }"
echo "   🛡️ Validation: patient_id zorunlu"
echo "   🔄 Response: { ok: true, encounter: {...} }"

echo ""
echo "🔍 MIDDLEWARE SIRASI KONTROL EDİLDİ:"
echo "   ✅ API routes (lines 1-10605) - ÖNCE"
echo "   ✅ Static middleware (lines 10609-10610) - SONRA"
echo "   ✅ Doğru sıralama - API route'lar HTML'den önce çalışır"
echo "   ✅ express.static() API'leri engellemiyor"

echo ""
echo "🛠️ DEBUG ADIMLARI (Frontend):"
echo "   1️⃣ URL düzelt:"
echo "      ❌ const url = '/api/encounter/start';"
echo "      ✅ const url = '/api/doctor/encounters';"
echo ""
echo "   2️⃣ Response debug logları ekle:"
echo "      const res = await fetch(url, options);"
echo "      const raw = await res.text();"
echo "      console.log('RAW RESPONSE:', raw);"
echo "      console.log('STATUS:', res.status);"
echo ""
echo "   3️⃣ JSON parse güvenli hale getir:"
echo "      if (res.ok) {"
echo "        const data = JSON.parse(raw);"
echo "        return data;"
echo "      } else {"
echo "        console.error('API Error:', raw);"
echo "        throw new Error(raw);"
echo "      }"

echo ""
echo "🛠️ BACKEND KONTROLLER (Güvenlik):"
echo "   ✅ Tüm API endpoint'leri JSON döndürüyor"
echo "   ✅ res.redirect() kullanımı yok"
echo "   ✅ Hata durumları: res.status(...).json({...})"
echo "   ✅ Middleware sırası doğru"

echo ""
echo "📊 BEKLENEN RESPONSE FORMATI:"
echo "   ✅ Başarılı:"
echo "     {"
echo "       ok: true,"
echo "       encounter: {"
echo "         id: 'uuid',"
echo "         patient_id: 'uuid',"
echo "         doctor_id: 'uuid',"
echo "         status: 'ACTIVE',"
echo "         created_at: '2026-02-16T...'"
echo "       }"
echo "     }"
echo ""
echo "   ❌ Hata:"
echo "     { ok: false, error: 'error_code' }"

echo ""
echo "🎯 FRONTEND FIX ÖRNEĞİ:"
echo ""
echo "// Önceki hatalı kod:"
echo "const response = await fetch('/api/encounter/start', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({ patient_id, notes })"
echo "});"
echo "const data = await response.json(); // ← JSON Parse Error"
echo ""
echo "// Düzeltilmiş kod:"
echo "const response = await fetch('/api/doctor/encounters', {"
echo "  method: 'POST',"
echo "  headers: { "
echo "    'Content-Type': 'application/json',"
echo "    'Authorization': 'Bearer ' + token"
echo "  },"
echo "  body: JSON.stringify({ patient_id, notes })"
echo "});"
echo ""
echo "const raw = await response.text();"
echo "console.log('STATUS:', response.status);"
echo "console.log('RAW RESPONSE:', raw);"
echo ""
echo "if (!response.ok) {"
echo "  console.error('API Error:', raw);"
echo "  throw new Error(raw);"
echo "}"
echo ""
echo "const data = JSON.parse(raw);"
echo "return data;"

echo ""
echo "✅ ÖZET:"
echo "   🎯 Ana sorun: Endpoint URL yanlış"
echo "   🎯 Çözüm: /api/encounter/start → /api/doctor/encounters"
echo "   🎯 Backend sağlam - middleware sırası doğru"
echo "   🎯 Tüm API'ler JSON response döndürüyor"
echo "   🎯 Frontend URL düzeltmesi sorunu çözecek"

echo ""
echo "🚀 SONUÇ:"
echo "   Endpoint URL düzeltildiğinde JSON parse hatası kaybolacak"
echo "   Backend zaten doğru çalışıyor"
echo "   Sadece frontend API çağrısı güncellenmeli"
