#!/bin/bash

echo "🔧 Treatment API Troubleshooting - Table Exists"
echo "=========================================="

echo ""
echo "✅ GOOD NEWS: Database table already exists!"
echo "   📄 encounter_treatments table is already created"
echo "   📄 No database setup needed"
echo "   📄 Focus on backend server restart"
echo ""
echo "✅ NEXT STEPS:"
echo ""
echo "🎯 Step 1: Check Table Structure (Optional)"
echo "   1. Open Supabase SQL Editor"
echo "   2. Execute: SELECT * FROM information_schema.columns WHERE table_name = 'encounter_treatments' ORDER BY ordinal_position;"
echo "   3. Verify required columns exist:"
echo "      - encounter_id (UUID)"
echo "      - tooth_number (TEXT)"
echo "      - procedure_name (TEXT)"
echo "      - status (TEXT)"
echo "      - created_by_doctor_id (UUID)"
echo "      - created_at, updated_at (TIMESTAMP)"
echo ""
echo "🎯 Step 2: Restart Backend Server"
echo "   1. Find the running server process:"
echo "      ps aux | grep 'node index.cjs'"
echo "   2. Kill the process:"
echo "      kill -9 <process_id>"
echo "   3. Restart the server:"
echo "      node index.cjs"
echo "   4. Look for treatment route registration:"
echo "      'Treatment routes registered' or similar message"
echo ""
echo "🎯 Step 3: Test API Endpoints"
echo "   1. Open the diagnosis screen in the app"
echo "   2. Check browser network tab for API calls"
echo "   3. Should see: GET /api/doctor/encounters/:id/treatments"
echo "   4. Should return: { ok: true, treatments: [] }"
echo "   5. Try creating a treatment with '+ İşlem Ekle' button"
echo ""
echo "✅ IF STILL GETTING ERRORS:"
echo ""
echo "🔍 Check Server Logs:"
echo "   1. Look for route registration errors"
echo "   2. Check for Supabase connection errors"
echo "   3. Look for 'cannot find module' errors"
echo "   4. Check for syntax errors in treatment routes"
echo ""
echo "🔍 Verify Route Registration:"
echo "   1. Check if routes/doctor/treatments.js exists"
echo "   2. Check if it's imported in index.cjs"
echo "   3. Look for: const doctorTreatmentRoutes = require('./routes/doctor/treatments');"
echo "   4. Look for: app.use('/api/doctor', doctorTreatmentRoutes);"
echo ""
echo "🔍 Test API Directly:"
echo "   1. Use curl or Postman to test endpoint"
echo "   2. GET: http://localhost:3000/api/doctor/encounters/YOUR_ENCOUNTER_ID/treatments"
echo "   3. Include Authorization header with JWT token"
echo "   4. Should return JSON response"
echo ""
echo "🔍 Check Frontend API Calls:"
echo "   1. In diagnosis screen, open browser dev tools"
echo "   2. Go to Network tab"
echo "   3. Filter by 'treatments'"
echo "   4. Check if requests are being made"
echo "   5. Check response status and body"
echo ""
echo "✅ QUICK TEST:"
echo ""
echo "🎯 Test with curl (if you have JWT token):"
echo "   curl -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "        http://localhost:3000/api/doctor/encounters/YOUR_ENCOUNTER_ID/treatments"
echo ""
echo "🎯 Expected Response:"
echo "   {"
echo "     \"ok\": true,"
echo "     \"treatments: []"
echo "   }"
echo ""
echo "✅ COMMON ISSUES:"
echo ""
echo "🔍 Server Not Restarted:"
echo "   ❌ Old routes still loaded"
echo "   ❌ New treatment routes not available"
echo "   ✅ Solution: Restart node index.cjs"
echo ""
echo "🔍 Missing Dependencies:"
echo "   ❌ Cannot find supabase module"
echo "   ❌ Cannot find verifyDoctor middleware"
echo "   ✅ Solution: Check file paths and imports"
echo ""
echo "🔍 Database Connection:"
echo "   ❌ Supabase connection failed"
echo "   ❌ Database credentials issue"
echo "   ✅ Solution: Check environment variables"
echo ""
echo "🔍 Route Registration:"
echo "   ❌ Treatment routes not registered"
echo "   ❌ Wrong path in app.use()"
echo "   ✅ Solution: Check index.cjs route registration"
echo ""
echo "🚀 TROUBLESHOOTING COMPLETE!"
echo ""
echo "✅ Summary:"
echo "   ✅ Database table exists (good!)"
echo "   ✅ Backend routes updated (done!)"
echo "   ✅ Need to restart server (critical!)"
echo "   ✅ Test API endpoints (next!)"
echo ""
echo "🎯 Most Likely Fix: Restart Backend Server"
echo "   The table exists and routes are updated, but the server needs to be restarted to load the new route definitions."
